[tool.poetry]
name = "idleon-save-editor"
version = "0.1.0"
description = ""
authors = ["desophos <1887450+desophos@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
plyvel = "^1.3.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.6-beta.0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
