name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0a2

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: poetry install --with test --no-interaction --no-root

      - name: Install package
        run: poetry install --with test --no-interaction

      - name: Run tests
        run: poetry run pytest --cov-report= --cov=idleon_saver --cov=scripts
        env:
          KIVY_GL_BACKEND: angle_sdl2

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ${{ github.workspace }}/.coverage

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: ${{ github.workspace }}/.coverage

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/.coverage:coverage.py
