name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: poetry install --with test --no-interaction --no-root

      - name: Install package
        run: poetry install --with test --no-interaction

      - name: Run tests
        run: poetry run pytest --cov-report= --cov=idleon_saver --cov=scripts

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/.coverage:coverage.py
